//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccidentProgram
    {
        public AccidentProgram()
        {
            this.Accident = new HashSet<Accident>();
            this.AlertAudit = new HashSet<AlertAudit>();
            this.Subscription = new HashSet<Subscription>();
        }
    
        public int Id { get; set; }
        public string ProgramName { get; set; }
        public string URL { get; set; }
        public string EmailTemplateID { get; set; }
        public string ProgramDescription { get; set; }
        public string ProgramDataElementDescriptions { get; set; }
    
        public virtual ICollection<Accident> Accident { get; set; }
        public virtual ICollection<AlertAudit> AlertAudit { get; set; }
        public virtual ICollection<Subscription> Subscription { get; set; }
    }
}
