//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertAudit
    {
        public long Id { get; set; }
        public int ProgramID { get; set; }
        public long SubscriberID { get; set; }
        public string message { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
        public virtual AccidentProgram AccidentProgram { get; set; }
    }
}
