//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobStatus
    {
        public long Id { get; set; }
        public int ProgramID { get; set; }
        public System.DateTime LastRunDateTime { get; set; }
        public string LastRunStatus { get; set; }
        public string LastRunErrorState { get; set; }
        public string LastRunError { get; set; }
        public int NewAccidentCount { get; set; }
        public Nullable<System.DateTime> ExportDateTime { get; set; }
    }
}
