//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public Subscriber()
        {
            this.Subscription = new HashSet<Subscription>();
            this.AlertAudit = new HashSet<AlertAudit>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public bool NotifyEmail { get; set; }
        public bool NotifySMS { get; set; }
    
        public virtual ICollection<Subscription> Subscription { get; set; }
        public virtual ICollection<AlertAudit> AlertAudit { get; set; }
    }
}
